### ISSUE TITLE
Unclear "name" in identity_auth_scope_v3

### ISSUE THREAD

**Issue by iitsDelbruegger** [opentelekomcloud/terraform-provider-opentelekomcloud#1064]
In the documentation of [identity_auth_scope_v3](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/identity_auth_scope_v3) it is unclear what the "name" parameter should be set to. At first, I thought I could just use some arbitrary string, but this did not work:

```Terraform
data "opentelekomcloud_identity_auth_scope_v3" "authscope" {
  name = "some_arbitrary_scope_name"
}
```

With this, I am getting:
```shell
Error: Resource not found: [GET https://iam.eu-de.otc.t-systems.com/v3/auth/tokens], error message: {"error":{"code":404,"message":"X-Subject-Token is invalid in the request","title":"Not Found"}}

  on variables.tf line 12, in data "opentelekomcloud_identity_auth_scope_v3" "authscope":
  12: data "opentelekomcloud_identity_auth_scope_v3" "authscope" {
```
My general access is working as I can create and change resources via Terraform.

As a result, I assume that I should use some scope name that somehow identifies my user or the token? I am authenticating via AK/SK and I don't know about such a name.

**Comment by outcatcher** [comment]
`name` itself bears little meaning. It's used just as a data source ID.

`X-Subject-Token is invalid in the request` seems to be caused by using AK/SK authentication.

Basically, the data source extracts auth scope from the currently used token. Needs investigation if this can be used with AK/SK. If not, documentation to be updated.
