### ISSUE TITLE
Error creating instance

### ISSUE THREAD

**Issue by ReenaAcharya** [opentelekomcloud/terraform-provider-opentelekomcloud#128]
Hi,

I am getting error while creating  instance using Terraform. Below is the code for instance used by me in Terraform:-
resource "opentelekomcloud_compute_instance_v2" "InstanceWeb1" {
  count           = "${var.instance_count}"
  name            = "${var.env}-${var.instanceweb1_name}}"
  image_name      = "${var.instanceweb1_image}"
  flavor_name     = "${var.instanceweb1_flavour}"
  key_pair        = "${opentelekomcloud_compute_keypair_v2.keypair.name}"
  security_groups = ["${opentelekomcloud_compute_secgroup_v2.SG1.name}"]
  network {
    uuid = "${opentelekomcloud_networking_network_v2.network.id}"
  }
  #tags = ["foo.bar", "tag.value"]
}

Error I am getting is as follows:-

Error applying plan:

1 error(s) occurred:

* opentelekomcloud_compute_instance_v2.InstanceWeb1: 1 error(s) occurred:

* opentelekomcloud_compute_instance_v2.InstanceWeb1: Error creating OpenTelekomCloud server: Invalid request due to incorrect syntax or missing required parameters.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Thanks,
Reena

**Comment by tstrohmeier** [comment]
I have a similar issue. 

In my case I increased the log level to `TF_DEBUG=TRACE` and `OS_DEBUG=1`. In the response from the API call you can see the error.

It would be good to display the `errCode` and `externalMessage` from the response in the error message above. 

Example:
``
opentelekomcloud_rds_instance_v1.test_db: Error getting instance from result: Invalid request due to incorrect syntax or missing required parameters. Reason: RDS.5013 Invalid database root password
``

**Comment by niuzhenguo** [comment]
@ReenaAcharya Can you please provide the detailed log with TF_LOG=DEBUG and OS_DEBUG=1.
@tstrohmeier I assume your issue is because the password provided is too weak.  Please refer to the API doc for the detailed requirement and I will try to copy that to the rds resource docs of opentelekomcloud provider.

**Comment by tstrohmeier** [comment]
@niuzhenguo Yes my password was too week but the problem was that it was very hard to debug. So what would be good is to display the detailed error, which is returned by the API. Currently the OTC Provider is just displaying a general and not very helpful error message. 

@niuzhenguo would it be possible to forward the error code & message from the API response? Enabling TF_DEBUG & OS_DEBUG is not working well in a Docker  environment.

**Comment by niuzhenguo** [comment]
We just changed to expose the real error message for 400 bad request instead of a general error, please check with the coming release, thanks!

**Comment by tstrohmeier** [comment]
@niuzhenguo When will you release v1.5.0?

**Comment by tstrohmeier** [comment]
#164

**Comment by niuzhenguo** [comment]
@tstrohmeier I would like to wait for iam resource #167. It's almost done.

**Comment by tstrohmeier** [comment]
@niuzhenguo:  Perfect. Thank you!
