### ISSUE TITLE
Question on release cycle

### ISSUE THREAD

**Issue by philippeckel** [opentelekomcloud/terraform-provider-opentelekomcloud#1413]
Hey all, 

first of all thanks for the good work @outcatcher, @lego963 and whoever is involved I might oversee.

I just wondered about the release cycle which apparently increased to more than 7 days now. Is there any specific reason? 

Apparently you're cleaning up code and improving tests; can we expect a major version `2.0.0` coming soon?

Any hint is more than welcome :-) 

Thanks,
Philipp

**Comment by outcatcher** [comment]
@philippeckel There are two general reasons, actually — the first is what you have said about: planning `v2` migration, the other one — we have less issues recently which we can fix on the provider side. That's why we skipped release previous week. We still plan `v1.25.5` to be release 22 or 23.09, but our main focus right now is making acceptance tests ready for CI 🙂 
After that we will be ready to concentrate on v1 -> v2 process.

**Comment by philippeckel** [comment]
Thanks a lot @outcatcher!

Looking forward and therefore closing this one ;-)
