### ISSUE TITLE
[ECS] Return admin password for windows machines

### ISSUE THREAD

**Issue by AdamVB** [opentelekomcloud/terraform-provider-opentelekomcloud#1777]
# Description of the enhancement

It would be great to have terraform return the admin password in the variables after a windows ECS has been created.

See: https://docs.otc.t-systems.com/api/ecs/en-us_topic_0161341998.html

**Comment by robert1x2** [comment]
Any updates here? When will it come?

**Comment by vladimirvshivkov** [comment]
> Any updates here? When will it come?

in next release

**Comment by vladimirvshivkov** [comment]
Feature is released in 1.31.5.
There 2 new fields: password and crypted password.
API requiers ssh private key for password decryption.
If you will set the `ssh private key path` you will get the plain password, otherwise you'll get encrypted.
Check documentation for command for password decryption.
API returns password after 5-10 minutes after instance creation.

If you will get any issues, please, comment.
