### ISSUE TITLE
Add deprecation warning for the DMS Queue and Group

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/terraform-provider-opentelekomcloud#1782]
Old DMS is going to be deprecated (https://open-telekom-cloud.com/en/support/release-notes/distributed-message-service/discontinue-dms-queue-end-of-june-2022). Let's drop it from docs now and later drop from the code.

**Comment by artem-lifshits** [comment]
Deprecation warning added.

Colleagues from orchestration squad mentioned that service shouldn't be available/supported since last week but as I can see it's still available both from console and API.

For now I'm leaving the ticket opened. Queue/groups code&documentation will be removed when it becomes completely unavailable.
