### ISSUE TITLE
elb opentelekomcloud_lb_listener_v2 doesn't have a way to set timeouts

### ISSUE THREAD

**Issue by xopher-mc** [opentelekomcloud/terraform-provider-opentelekomcloud#1910]
# Description of the enhancement
In the gui it is possible to set time outs for the listener
<img width="578" alt="image" src="https://user-images.githubusercontent.com/5712436/187430191-33ac7a0d-ba04-4670-948e-affe6144a354.png">

In console it appears that the elb.opentelekomcloud_lb_listener_v2  object does have a timeouts property, but it is not documented how to set it. 

`"timeouts" = null /* object */`

**Comment by anton-sidelnikov** [comment]
Hello @xopher-mc ,
Sorry, but api does not support timeouts feature for v2. Internal incident created: OST-17914

**Comment by anton-sidelnikov** [comment]
Sorry but it will not be fixed, info from devs: Actually Elbv2 (Shared load balancer) can not modify its listener timeout values due to its shared nature. This feature was introduced for dedicated loadbalancers (Elbv3) but since the console interface is shared, the setting can be seen for ELBv2 as well. customers will be notified via the GUI that timeout values are not applicable to ELBv2, thanks in advance!
