### ISSUE TITLE
Change of CCE Cluster Annotation for ICAgent installation 

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2157]
Hi,
opentelekomcloud/latest/docs/resources/cce_addon_v3 needs to be upated.

For the old 1.23 CCE release the annotation for automatically isntalling icagent was in terrafrom code: 
annotations = { "cluster.install.addons.external/install" = "[{\"addonTemplateName\":\"icagent\"}]" }

But for the new 1.25 CCE release it changed.
The current values seems to be:
annotations = { "cluster.install.addons.external/install" = "[{\"addonTemplateName\":\"icagent\",\"extendParam\":{\"logSwitch\":\"true\",\"tDSEnable\":\"true\"}}]" }

That change also seems to affect new 1.23 clusters installations. With the old annoation, the ICAgent is no longer installed for new cluster.

**Comment by anton-sidelnikov** [comment]
Hi! @CHS-OTC, for me ICagent installed successfully with annotations = { "cluster.install.addons.external/install" = "[{"addonTemplateName":"icagent"}]" } and cluster_version = "v1.25"

![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/53078276/1f0048a2-addd-44a6-8cab-5619df17dc43)
also installed for 1.23
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/53078276/9a13e137-642f-4e7f-a25c-b7eb11f9d604)

but this is also valid: annotations = { "cluster.install.addons.external/install" = "[{"addonTemplateName":"icagent","extendParam":{"logSwitch":"true","tDSEnable":"true"}}]" }

I did not see the real reason to add this into doc, because official docu not contains this: https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/cluster_management/creating_a_cluster.html
