### ISSUE TITLE
Support for SFS Turbo Standard Enhanced and Performance Enhanced

### ISSUE THREAD

**Issue by svenreppin** [opentelekomcloud/terraform-provider-opentelekomcloud#2313]
# Description of the enhancement
Using the console, you are able to create SFS turbo with the flavor STANDARD, PERFORMANCE, STANDARD_ENHANCED and PERFORMANCE_ENHANCED. First both can be managed with current provider, but the ENHANCED flavors can not be created via terraform. Is it possible to make it available, please?

**Comment by gorapatrik** [comment]
Hello @artem-lifshits 

Can you please help us with the following issue with enhanced shares?

We have tried to create an SFS with terraform apply, using 

resource "opentelekomcloud_sfs_turbo_share_v1" "SFS_enhanced_test2" {
  name              = "SFS_enhanced_test2"
  size              = 500
  share_proto       = "NFS"
  share_type        = "STANDARDENHANCED"
  
  with provider verion:
  version         = "1.35.7"
  
  We get the following error messages:
![terraform2](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/101478625/d9d8b5e2-fab8-4628-9321-ace6d58165bf)
![terraform1](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/101478625/59cd137f-088f-4f60-b525-06da838de1bf)

Even after changing the provider version, and making a terraform init -upgrade,
we still cannot create enhanced shares. 

Any suggestions on the "share type" value or the size value? Do we need to change something
so that the size is accepted or is is because the valuse of share type is incorrect?
Thank  you!

**Comment by artem-lifshits** [comment]
Hello @gorapatrik! New provider version with SFST enhanced support will be today.
I will ping you here when it's done.

**Comment by artem-lifshits** [comment]
@gorapatrik @brieseme please check latest release.

**Comment by gorapatrik** [comment]
Dear @artem-lifshits 
I have checked, and the unsupported argument error does not appear anymore for "enhanced".
Still the size error is  present 

` Error: error creating OpenTelekomCloud SFS Turbo: Bad request with: [POST https://sfs-turbo.eu-de.otc.t-systems.com/v1/35c5c77fc8fb4de3b0f3ce550ce585fa/sfs-turbo/shares], error message: {"errCode":"SFS.TURBO.0008","errMsg":"invalid size:10240, should between 0 and 0"}
│
│   with opentelekomcloud_sfs_turbo_share_v1.SFS_enhanced_test2,
│   on main.tf line 5, in resource "opentelekomcloud_sfs_turbo_share_v1" "SFS_enhanced_test2":
│    5: resource "opentelekomcloud_sfs_turbo_share_v1" "SFS_enhanced_test2" {
`
does this suggest an error in the code? it does not matter what I try 
size = 500
or
size = 0
or 
size = 1024
same error message is thrown that the value "should be between 0 and 0"

**Comment by artem-lifshits** [comment]
@gorapatrik could you post your TF resource code please?
Also documentation states that enhanced shares capacity ranges from 10240 to 327680:
https://docs.otc.t-systems.com/scalable-file-service/api-ref/sfs_turbo_apis/lifecycle_management/creating_a_file_system.html#

**Comment by gorapatrik** [comment]
Hello @artem-lifshits 

Now it worked with the size. But still we cannot create it with code, and also not manually in OTC.
We have tried 2 different subnets also.
A normal SFS can be created with code and manually, but enhanced neither with code, nor manually.

Terraform error message:

` Error: error waiting for SFS Turbo (d8b96dff-dc48-45bb-aa5d-cf95a95600eb) to become ready: unexpected state '303', wanted target '200'. last error: %!s(<nil>)
│
│   with opentelekomcloud_sfs_turbo_share_v1.SFS_enhanced_test2,
│   on main.tf line 5, in resource "opentelekomcloud_sfs_turbo_share_v1" "SFS_enhanced_test2":
│    5: resource "opentelekomcloud_sfs_turbo_share_v1" "SFS_enhanced_test2" {


Terraform main.tf

resource "opentelekomcloud_sfs_turbo_share_v1" "SFS_enhanced_test2" {
  name              = "SFS_enhanced_test2"
  share_proto       = "NFS"
  share_type        = "STANDARD"
  vpc_id            = "var.vpc_id"
  subnet_id         = "var.subnet_id"
  security_group_id = "var.sg_id"
  availability_zone = "var.az"
  size              = 10240
  enhanced          = true
}`

**Comment by artem-lifshits** [comment]
@gorapatrik it's tenant related issue, please open ticket for OTC support.
