### ISSUE TITLE
Problems with provider signature in openTofu registry

### ISSUE THREAD

**Issue by steffeneichler** [opentelekomcloud/terraform-provider-opentelekomcloud#2470]
# Tofu provider version

tofu v1.6.2

# Affected Resource(s)

tofu init command

# Tofu Configuration Files

code not affected

# Debug Output/Panic Output

```
╷
│ Error: Failed to install provider
│ 
│ Error while installing registry.opentofu.org/opentelekomcloud/opentelekomcloud v1.36.4: authentication signature from unknown issuer
╵
 ```

# Steps to Reproduce

1. `tofu init -upgrade` on a stack including opentelekomcloud related resources

# Expected Behavior

no failure during init

same version of provider loaded via origin hashicorp registry is validated successfully

# Actual Behavior

```
╷
│ Error: Failed to install provider
│ 
│ Error while installing registry.opentofu.org/opentelekomcloud/opentelekomcloud v1.36.4: authentication signature from unknown issuer
╵
```

# Important Factoids

not relevant

# References

**Comment by steffeneichler** [comment]
Ticket also opened in opentofu registry project.
https://github.com/opentofu/registry/issues/321

**Comment by ghost** [comment]
Hey folks, OpenTofu dev here.

Currently, the OpenTofu registry does not contain a GPG key for this provider. In order to publish the GPG key in the OpenTofu registry,  a member of this GitHub organization (`opentelekomcloud`) needs to [make their membership in the organization public](https://github.com/orgs/opentelekomcloud/people) and then [submit the GPG key here](https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+&namespace=opentelekomcloud). Unfortunately, we cannot perform this step automatically, which is why the key is currently missing.

If you have any further questions, please feel free to ping us either here or on the OpenTofu Slack.

**Comment by anton-sidelnikov** [comment]
Hi @steffeneichler gpg key added: https://github.com/opentofu/registry/issues/396
