### ISSUE TITLE
Difference between opentelekomcloud_ecs_instance_v1 and opentelekomcloud_compute_instance_v2?

### ISSUE THREAD

**Issue by dschemp** [opentelekomcloud/terraform-provider-opentelekomcloud#2546]
What is the difference between the resources `opentelekomcloud_ecs_instance_v1` and `opentelekomcloud_compute_instance_v2`? That isn't clear from the docs and may even look like they are two completely different things (although I guess they are the same other then the version?)

**Comment by anton-sidelnikov** [comment]
Hi @dschemp, this is different apis, compute is openstack api, and ecs otc custom api. You can use both, they provide almost the same options for ECS instances

**Comment by dschemp** [comment]
Is there any preferation on which one to use? Nonetheless it would be helpful to add this to the docs.

**Comment by anton-sidelnikov** [comment]
It’s best to start with the API documentation since all resources are based on it. Both resources are generates ECS instances, so the choice depends on your familiarity. If you’re comfortable with OpenStack, go with the OpenStack option, otherwise, choose any. The Terraform provider documentation only includes essential information specific to provider. Official providers for any cloud platform typically do not contain detailed API information or user guides.

**Comment by anton-sidelnikov** [comment]
If you have additional questions please left it in #2547, close this as related issue.
