### ISSUE TITLE
CSS - Terraform documentation doesn't corresponds to CSS API documentation

### ISSUE THREAD

**Issue by mikacur** [opentelekomcloud/terraform-provider-opentelekomcloud#2591]
In CSS documentation for Terraform is mentioned that parameters 
[enable_https](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/css_cluster_v1#enable_https)
[enable_authority](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/css_cluster_v1#enable_authority)

are optional but in API call documentation is information that those parameters are mandatory.
https://docs.otc.t-systems.com/cloud-search-service/api-ref/cluster_management_apis/changing_the_security_mode.html

**Comment by anton-sidelnikov** [comment]
Hi @mikacur, thanks, i will update documentation soon

**Comment by anton-sidelnikov** [comment]
The provider documentation may slightly differ from the API documentation because provider is a complex solution that can use many different endpoints within a single resource. To synchronize them correctly, we may change the default values and parameter requirements. The mentioned parameters are always passed when creating a resource, but their default value is `false`. I have corrected this in the documentation

**Comment by anton-sidelnikov** [comment]
Documentation updated in 1.36.15
