### ISSUE TITLE
[ELB] Request for New Features: Support create elastic ELB( Elastic Load Balancer ) instance.

### ISSUE THREAD

**Issue by Jambo-sudo** [opentelekomcloud/terraform-provider-opentelekomcloud#2740]
# Description of the enhancement
Hello Team,

I'm submitting this feature request for the Terraform provider to support specifying an elastic instance type when creating an Elastic Load Balancer (ELB). This feature would be particularly useful for us.

Best

**Comment by TaoLiu-TSI** [comment]
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/2742
@Jambo-sudo

**Comment by anton-sidelnikov** [comment]
Hi @Jambo-sudo  @TaoLiu-TSI, please check the documentation first, before creating request: https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_loadbalancer_v2

**Comment by uhla** [comment]
Hi @anton-sidelnikov, what would be the correct way to specify the elastic type ELB (not fixed one)? All I can find is ability to specify the ELB L4 flavors, but can't find anything on specifying I'd like to use the elastic one. Basically way to get ELB charged by LCU instead of by fixed instance type. Thanks!

Talking about this part of the configuration: 

<img width="420" height="71" alt="Image" src="https://github.com/user-attachments/assets/7962abf4-970d-4713-a3f8-8ccbdb7c8be3" />
