### ISSUE TITLE
VPNaaS tag support

### ISSUE THREAD

**Issue by lnobach** [opentelekomcloud/terraform-provider-opentelekomcloud#502]
Tag support for the [VPNaaS service](https://www.terraform.io/docs/providers/opentelekomcloud/r/vpnaas_service_v2.html) should be added.
This is possible according to the [OTC API](https://docs.otc.t-systems.com/api/vpn/en_topic_0093011486.html#en_topic_0093011486__en-us_topic_0103470566_table14751112719406).

**Comment by ShiChangkuo** [comment]
@lnobach According the [OTC API](https://docs.otc.t-systems.com/api/vpn/en_topic_0093011486.html), we can add tags on [VPNaaS site connection](https://www.terraform.io/docs/providers/opentelekomcloud/r/vpnaas_site_connection_v2.html) which is the visible resource in VPNaaS console, rather than VPNaaS service.
