### ISSUE TITLE
Please add email addresse when creating new user, so initial password will can be send to user via mail

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud/terraform-provider-opentelekomcloud#551]
Can you please add the email adresse as property when creating new user? This would trigger new user receiving one click mails via that way. Thank you.

**Comment by raypettersen** [comment]
This is something we'd like to see as well. +1

**Comment by Nils-Magnus** [comment]
Could you please add some context? In which situation do you want to add the email address?

What is your expected behavior?

What is the actual behavior?

**Comment by gtema** [comment]
Short info from platform:
- email sending is not supported by the platform for changes through API. A Demand is created (no estimation on when/whether it will be delivered)
- new DM is for adding separate API to trigger sending email. We can't integrate this into the currently used APIs due to the compatibility issues (this functionality doesn't exist in OpenStack and is a "feature" of the platform, that can be delivered only in a compliant way)
- API supports properly setting email as a user modification (not under "extra" block)
- API has a bug, that upon user creation email is respected only if it is passed under the "extra" block, which is definitely a bug, but for the moment seems also to be the same what openstack provider is doing.

With this issue I would suggest for the beginning adding support for passing email for user creation and update. Email sending can be addressed only when corresponding service is deployed to the platform.

**Comment by outcatcher** [comment]
Implemented in the latest release (v1.21.2)
